# Generated by Django 3.0.6 on 2020-06-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200621_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='aboutImages',
            field=models.ImageField(blank=True, null=True, upload_to='aboutImages/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
