# Generated by Django 3.0.6 on 2020-05-30 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_about_about_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='about_key',
        ),
    ]
